spring.application.name=15_SBMS_API_Gateway


server.port=8080


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true


#spring.cloud.gateway.routes[0].id=employee-service
#
#spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE-SERVICE
#
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/employee/**
#
#
#
#spring.cloud.gateway.routes[1].id=department-service
#
#spring.cloud.gateway.routes[1].uri=lb://DEPARTMENT-SERVICE
#
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/department/**

spring.cloud.gateway.server.webflux.routes[0].id=ttd-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://TTD-SECURITY
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/**


#spring.security.user.name=ttd
#spring.security.user.password=123
server.servlet.session.timeout=2m

spring.webflux.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/



management.tracing.enabled = true
management.tracing.sampling.portability=1.0